### PR TITLE
Add long description to rules

### LINKED ISSUE #11: Add optional explanations to the test descriptions
It would be nice to have explanations for the tests. For instance, I'm puzzling over why you should avoid `__DIR__` and `__FILE__`. An option to explain the whys would be great.

### PR DESCRIPTION
**Pull request by hanneskod**
Adds `getLongDescription` to rules and displays said descriptions with `RulesCommand`.

`DocblockDescriptionTrait` reads description and long description from the class level doc comment. Se `src/Rule/DisplayErrors.php` for a concrete example. And execute `bin/psecio-parse rules displayerrors` to view the generated output.

`eloquent/blox` is used to parse the docblock.

`RuleCollection` rewritten to be case insensitive.

Merging will close #11.

### CODE REVIEW

**Comment by enygma** [comment]
Hmm, I wonder why this one can't be merged clean anymore...I'll have to check it out later on.

**Comment by redbeardcreator** [comment]
The progress bar touch several files. I had to fix a merge conflict on #52.

**Comment by hanneskod** [comment]
As `eloquent/blox` didn't work in #52 it should probably not be used here.. Lets see if we can go in a different direction..

**Comment by redbeardcreator** [comment]
Well, I'm not sure. I had a thought on what might be wrong not too long after I left this morning. I'm going to give it a second shot. I think it just may be struggling with the `/** @tag */` structure. If that's the case, I can do a fix up on it. Again, it means patching blox, but I think it may work. I hope to have time tonight to look at it.

**Comment by hanneskod** [comment]
I resolved the conflicts, so this can be assesed and merged. If you like where I am going with this I would suggest a merge now, and if for some reason `eloquent/blox` is not used in #52 we can remove it from `DocblockDescriptionTrait` in another pr.

(If you don't want to merge at this stage I can put the updates of `RuleCollection` in a different pr...)

**Comment by redbeardcreator** [comment]
I'll be reviewing this sometime today. Probably after 9:00 PM US CST, but might happen in the next hour or so.

**Comment by redbeardcreator** [comment]
While I'd like to see more work on how the long description is actually set up, I'm quite happy with the direction. I'm merging, and will comment more on the long description in a bit.

**Comment by redbeardcreator** [comment]
I'd like to suggest that we add additional formatting for the long descriptions (things like <func> and <setting>, as well as well defined sections. But I think it should grow organically first and that should happen later, once everything that is needed is identified.

**Comment by hanneskod** [comment]
Yep. I agree!

**Pull request merged**
