### PR TITLE
Test for more "sensitive values"

### PR DESCRIPTION
**Pull request by redbeardcreator**
The `TestAvoidHardcodedSensitiveValues` test was missing some sensitive values. So I added them and refactored the `evaluate()` method.

### CODE REVIEW

**Comment by hanneskod** [comment]
Yupp, looks good. :+1: for merging..

**Comment by enygma** [comment]
Nice additions - do you think there's any other types we might need to add? I can't think of other common names off the top of my head, but there have to be more than just username or password...

**Comment by hanneskod** [comment]
Maybe `pswd`. I know I have used that :smile:

**Comment by redbeardcreator** [comment]
I'm considering adding things like `$awskey` and `$awssecret`, probably just plain secret as well. Maybe something like the regular expression `/([\w]+_?)secret/i` I don't think we can do the same thing with `key`. I know I use it by itself and in various forms all pretty frequently. But `secret`... there's generally only one use for that. What other common services that use key/secret pairs should we include? I'm sure there are plenty, but AWS is the only one I've used.

**Comment by redbeardcreator** [comment]
I'd like someone to check over the new regex checks for me before I merge this in.

Also, I just realized it should handle `const USERNAME = "name";` and `define("USERNAME", "name");`. That's work that I probably won't be able to do tonight.

**Comment by hanneskod** [comment]
Yes, checking for constants is a great addition!

I am thinking the regexp could be simply `/secret/i`. That would also match `$secret_key` and stuff like that..

**Comment by enygma** [comment]
Yeah, I think "secret" is a good addition...I could see it leading to a few false positives, but not as many as it would useful results :)

**Comment by redbeardcreator** [comment]
@hanneskod, hmmmm. I wonder if it would make sense to just do a substring match on all the values. So `$sftpUser`, `$sftpPassword` and the like are matched.

**Comment by hanneskod** [comment]
Yes I can't see wy not..

**Comment by redbeardcreator** [comment]
Something to work on tonight...along with the annotation handler.

**Comment by redbeardcreator** [comment]
I'm fairly certain this is now done. Well, until the sensitive values list is expanded again :wink:

It includes:
* Prefix, suffix and exact match tests against several sensitive value indicators. This is reduced checking compared to the previous suggestion of just doing substring match. I'm afraid full substring matches may be more likely to generate false positives.
* Validation of variable assignments, `const` declarations and `define` calls.

Assuming this all checks out, it's ready for merging.

**Comment by hanneskod** [comment]
Yes it looks good to me. Merging.

**Pull request merged**
