### PR TITLE
Add travis support

### PR DESCRIPTION
**Pull request by hanneskod**
Whit the test suite getting better and the coming merge of pr #26 it might be time to start using travis. I think this config is extra neat as it runs parse on itself.

Also adding some shiny badges to reamde..

### CODE REVIEW

**Comment by hanneskod** [comment]
I did a travis test run and saw some unit tests failing. This is my bad, a fix will come in another pr..

https://travis-ci.org/hanneskod/parse

**Comment by enygma** [comment]
Oops :) k...let me know when it's updated

**Comment by hanneskod** [comment]
Will do. I think it is safe to merge this anyway, as this pr only contains the travis setup..

**Comment by enygma** [comment]
Sounds good, thanks!

**Pull request merged**
