### PR TITLE
Add command tests

### PR DESCRIPTION
**Pull request by hanneskod**
Add some tests for the command classes. These tests are somewhat slow at the moment. Specially `ScanCommand` could probably be refactored with some dependency injection to speed things up. However some tests are better than no tests..

I'm aware that some of the pull requests I have been submitting this morning might need updates when #26 is merged. I'm happy to resolve these issues as they become apperent (#26 should be first in line here i guess).

This concludes a busy morning of pull requests =). I had a list of things I wanted to do, and just sat down and did them...

### CODE REVIEW

**Comment by hanneskod** [comment]
`ScanCommandTest` is now much faster. Once #26 is merged I will fix the test path and then this can be merged too.

**Comment by redbeardcreator** [comment]
I like how you're setting up the files. Perhaps we should move that into a base class and use it with `FileIteratorTest`. Once #26 is merged.

**Comment by hanneskod** [comment]
Yes it's a good idea for `FileIteratorTest` as well. Not sure we need a base class for it though..

**Comment by redbeardcreator** [comment]
My rule of thumb is if you do it once, fine. Twice, think really hard about refactoring so it can be shared. Three times, refactor. So, I can go either way at this point.

**Comment by hanneskod** [comment]
This is ready to merge. I am not sure how to do this. Maybe amongst the three of us we could say that two votes for and none against means it's ok to merge? As long as the suggested changes are not major anyways..

**Comment by redbeardcreator** [comment]
I moved the discussion of how to merge to #41.

I've checked over the code for the PR and I think it looks good.

:+1:

**Pull request merged**
