### PR TITLE
Rename tests

### LINKED ISSUE #49: Test name consistency
As I continue my preliminary thinking on #10, I've been looking at test names. I've come to the realization that they are very inconsistent. Some start with `Avoid`, some start with `Use`, and both mean the same thing (avoid this; you're using this bad thing). Then some tests don't have a prefix at all. It seems @enygma named them organically (as would I).

I'd like to propose, before there's a code-level end-user reason to refer to the names, that we consider making the names more consistent. I know [naming things is hard](http://martinfowler.com/bliki/TwoHardThings.html), so I propose we come up with a naming convention. This is a (long) starting point. I may have it completely wrong, so feel free to critique and criticize. Or compliment if I got things right :smile: 

The part between the triangles (:small_red_triangle: :small_red_triangle_down:), or more likely an edited version, would go in developer documentation.

:small_red_triangle: 
## Naming tests
Test names should be consistent throughout the test suite. To help ensure this, we use a simple naming convention:

```
<what><optional-when>
```

That is, we name *what* the test is about and potentially add some modifiers saying *when* it should be tested..

An example of just a *what* would be `Eval`. Since `eval()` is (almost) always bad, we don't need to modify the test name. Another would be `BooleanEquality`, which enforces always using the identical operator (`===`) instead of the equals operator (`==`).  There's not much more involved in the concept so a modifier isn't needed.

An example of a *when* modifier is `EchoWithFileGetContents`. In general, using `echo` is safe and necessary. However, `echo file_get_contents()` is potentially a bad thing. There is potential for several tests to be about using `echo` with something dangerous; adding `WithFileGetContents` makes it clear what's being tested.
:small_red_triangle_down: 

### Notes
1. I intentionally omitted the `Test` prefix. More discussion below.
2. The examples are just that...there might be better ones to use. I'm also using the updated names I propose below.

## Discussion
I've found using `Test` as a prefix to be cumbersome. I really don't mind it in code (although `Tests\Eval` is also workable). But on the command line and in annotations, it will be quite cumbersome. These are all about tests, so specifying `Test` probably isn't necessary. So I'd personally like to see any UI not include the `Test` prefix. As a result,`--include-tests` and `--exclude-tests` would use the prefix-less version (or at least support it) and annotations would use the non-prefixed version. It's easy enough to add the prefix in code.

I think we're rapidly nearing the last reasonable time to rename the tests, so if it's going to happen, it needs to happen soonish.

### Updated test names
The following are my proposed name changes. I'm leaving `Test` out at this point as a convenience. I have not yet verified each one of these (although I did verify several), so some may be incorrect.

Old Name | New Name
---------|----------
AvoidGlobalsUse	              | GlobalsUse
AvoidHardcodedSensitiveValues | HardcodedSensitiveValues
AvoidRequestUse               | RequestUse
DisableDisplayErrors          | DisableDisplayErrors
EchoWithFileGetContents       | EchoWithFileGetContents
Eval                          | Eval
ExitOrDie                     | ExitOrDie, or just Exit
ExtractNotOverwrite           | Extract
HttpRawPostData               | HttpRawPostData
ImportRequestVariables        | ImportRequestVariables
LogicalOperatorsFound         | NamedLogicalOperators
NoEregFunctions               | EregFunctions
OutputWithVariable            | OutputWithVariable
SessionRegenFalse             | SessionRegen
SetHeaderWithInput            | SetHeaderWithInput
UseExecModifierInRegex        | RegexWithExecModifier
UseMysqlRealEscapeString      | MysqlRealEscapeString
UseParseStr                   | ParseStr
UseReadfile                   | Readfile
UseRunkitImport               | RunkitImport
UseSystemFunctions            | SystemFunctions
UseTypeCheckEqualsOnBoolean   | BooleanEquality

### PR DESCRIPTION
**Pull request by hanneskod**
A lot of renaming :smile: 

Some devitaions from @redbeardcreator's suggestion:

* `SessionRegenerateId` instead of `SessionRegen`
* A simple `Eval` was not possible as the name collides with the actual `eval()` function. I used `EvalFunction` instead.

I put the naming convention in `CONTRIBUTING.md`, along with some other guidelines (see if you like).

I also moved `ParseTest` to the `Rule` namespace as `Rule\RuleTestCase` and made some minor changes to comply with psr-2.

Instead of changing the `list-tests` command to `list-rules` I opted for `info`. I have this idea that we could supply more educational help about to checks being made using the info command

    psecio-parse info logicaloperators

I will describe this idea more clearly another day (now sleep!) :smile: 

Merging will close #49.

### CODE REVIEW

**Comment by redbeardcreator** [comment]
Except for a few comments I made on the individual commits (and I don't know how they show up to you...I don't see them at the moment :frowning:) I think this looks really good.

I like the idea behind the `info` command. I think it will address #11 when it's fully realized. Although maybe `rules` is a better name. `psecio-parse rules` and `psecio-parse rules logicaloperators` feels a little better to me. I'd almost want `psecio-parse info` to provide pointers to general security-conscious programming notes/websites/*info*. Of course, then I'd want to add justification links to the rule details pages. And I could go on but I'll wait for your further explanations :stuck_out_tongue_winking_eye: 

I agree with the guidelines and am a fan of PSR-2. Maybe it's just because it mostly aligns to my personal preferences as they have built up over the years (gah...24+ years programming professionally; makes one feel old :open_mouth:).

**Comment by redbeardcreator** [comment]
Oh...there they are :expressionless:

**Comment by hanneskod** [comment]
You are quite right about `@return void`. I used it til recently, then I started using apigen to render api documentation, and apigen dosn't render void. Didn't know about the psr-5 draft, thanks for pointing it out.

`rules` works for me. I will add comments to #11 soonish.

> I agree with the guidelines and am a fan of PSR-2. Maybe it's just because it mostly aligns to my personal preferences as they have built up over the years (gah...24+ years programming professionally; makes one feel old :open_mouth:).

:smile: Off topic: what do you think about adding a code sniffer check to the travis builds? Maybe it's overenthusiastic, but I think it makes the code base easier to maintain in the long run...

I also added some lines to `.gitignore`. For local development stuff that I don't want to commit accidentally.

**Comment by redbeardcreator** [comment]
Local development stuff should probably go in your local [`.git/info/exclude`](https://help.github.com/articles/ignoring-files/#explicit-repository-excludes) file. That is ignored as well, but doesn't get shared. If it's something you use on most of your projects, you can also put it in your global `.gitignore` file.

**Comment by hanneskod** [comment]
Ok, thanks. Reverting.

**Comment by hanneskod** [comment]
If there are no more comments on this it could maybe me merged later today..?

**Comment by enygma** [comment]
Yeah, sorry - I haven't really gotten a chance to look through it yet, but honestly, I'm sure it's fine as long as everything with the tests pans out too.

**Comment by hanneskod** [comment]
No problem. Just a little impatient..

Merging.

**Comment by redbeardcreator** [comment]
Yeah, I just had to take a night off. However, you had addressed all my concerns so it's all good.

**Comment by hanneskod** [comment]
Well deserved!

**Pull request merged**
