### PR TITLE
Cleaned up version of readable-tests

### PR DESCRIPTION
**Pull request by redbeardcreator**
This replaces PR #23. Please see discussion there, but continue here. The new PR was necessary because I bungled merging in #25. I might have been able to recover, but this was easier.

This PR implements most of @hanneskod's suggestions for #23, with some modifications.

I also flattened the tests directory structure a bit by switching to PSR-4 on the tests. I went ahead and applied this to all the tests, not just the ones created here. I'd recommend doing this for the whole project. Makes it much cleaner.

### CODE REVIEW

**Comment by hanneskod** [comment]
Ah, thinking outside the box with psr-4. Now we can have any namespace and still a great directory structure. Perfect!

I think the rest of the code should also be moved to psr-4, but that is i different pr of course.

Adding more information to failure messages with something like `var_dump` also sounds really good. I'm sorry if I had a negtive tone commenting this, achieving the cleanest solution sometimes carries my away a bit..

Now I think this looks really good. Let the testing begin!

**Comment by hanneskod** [comment]
One more comment =)

As the tests (not the unit tests but the `\Psecio\Parse\Tests`-tests) no longer takes any arguments in the constructors the `false` argument used in `buildTest` when creating each test is no longer necessary..

**Comment by redbeardcreator** [comment]
Ah, I hadn't noticed that. I'll try to fix tonight. Makes me wish I had a more reliable laptop to work on...I'll be waiting for an hour at lunch with nothing to do...

**Comment by redbeardcreator** [comment]
@hanneskod The new messages should be quite a bit more informative, but the way things are set up at the moment, there's not enough info available to do something like a `var_dump()`. It will take some further refactoring. I like having the separate `scan()` method, but I think it should be modified it at some point to return more than just a bool. It holds all the pieces. Another approach would be to test whether the assertion will fail and then re-parse the code and use that. It feels a little clunky but should be effective.

As far as the tone of your comments, I thought they were generally constructive. Thank you.

**Comment by hanneskod** [comment]
> Another approach would be to test whether the assertion will fail and then re-parse the code and use that. It feels a little clunky but should be effective.

Yeah, I'm sure there are many good solutions here. When the tests start to fail in confusing ways it might be clearer what needs to be done =)

> As far as the tone of your comments, I thought they were generally constructive. Thank you.

Good to hear. Sometimes it's hard to know what emotions you transmit in written text..

**Comment by redbeardcreator** [comment]
I've added all the `ParseTest`s I can before I start modifying the actual Tests. Well, I could add `TestUseTypeCheckEqualsOnBooleanParseTest`, but it has the whole line checking issue mentioned in #27. I have to ponder that before attacking it.

**Comment by redbeardcreator** [comment]
I had to do a bit more work with FileIteratorTest, as @hanneskod added a couple more tests and I had completely moved it... Should all be good, now.

**Comment by hanneskod** [comment]
@redbeardcreator I just realised that pr #35 alters some tests that you mave moved in this pr. Sorry about that. Again it happens..

**Comment by redbeardcreator** [comment]
It's ok. I'll get it cleaned up tonight.

**Comment by hanneskod** [comment]
I am not sure about `composer.lock`, I don't think it should be added.

And I am curious, why did you change `FileIteratorTest`. Maybe a different pr?

**Comment by redbeardcreator** [comment]
Compose recommends including composer.lock in your repository. That way, anyone who uses your project gets the exact same versions of libraries as you develop with.

I had to change `FileIteratorTest` because I removed a file (a test that wasn't needed anymore) and it broke. So I added a set of files to test against that aren't tests that might change. Perhaps I was a bit aggressive in changing the test, though. I can back out everything except what's explicitly needed to make the test work again.

**Comment by redbeardcreator** [comment]
Of course, I'm not opposed to moving `composer.lock` back out. Maybe it should be in a different PR.

**Comment by redbeardcreator** [comment]
@hanneskod Nothing broke from that, per se. I just got heavy handed in fixing things. I'm rolling back the `composer.lock` file

**Comment by enygma** [comment]
Is this currently in a state where it is stable or is there more work to be done?

**Comment by hanneskod** [comment]
If @redbeardcreator is satisfied I feel this is ready to merge.

**Comment by redbeardcreator** [comment]
It's ready. There may be follow-on work, but the code here is ready.

**Comment by redbeardcreator** [comment]
Since I just discovered I'm now a collaborator...

**Comment by enygma** [comment]
woot! I figured it'd be easier than you guys having to wait on me to get these merged (only so much time in the day :( )

**Comment by redbeardcreator** [comment]
@enygma I know that feeling! Thanks, by the way.

**Comment by enygma** [comment]
@redbeardcreator no problem - thanks for the awesome work :)

**Pull request merged**
