### PR TITLE
Enable scan paths to be filenames

### PR DESCRIPTION
**Pull request by hanneskod**
A simple pr that makes it possible to scan individual files

```
bin/parse scan src/Psecio/Parse/Tests/TestLogicalOperatorsFound.php
```

### CODE REVIEW

**Comment by hanneskod** [comment]
Oops, I missed handling to file-does-not-exist case. Fix comming..

**Comment by hanneskod** [comment]
Done..

**Comment by enygma** [comment]
Cool - thanks for adding the test too! Merging.

**Comment by redbeardcreator** [comment]
Cool...I've been wanting this!

**Pull request merged**
