### PR TITLE
Add "unit" tests that test against parsed code

### PR DESCRIPTION
**Pull request by redbeardcreator**
Implements Issue #22.

Under `tests/Psecio/Parse`, implemented `ParseTest.php`,
`ParseTestVisitor.php` and `Tests/TestSessionRegenFalse_ParseTest.php` (yeah,
crazy name there. May need to figure out a better naming convention).

* `ParseTest.php` implements an abstract base class for all the parsing-based
  tests.
* `ParseTestVisitor.php` implements a simple parse tree visitor for use in
  testing.
* `Tests/TestSessionRegenFalse_ParseTest.php` implements several parse string
  tests for `TestSessionRegenFalse`, including one for the problem I found and
  fixed in PR #15.
* `Tests/TestAvoidGlobalsUse_ParseTest.php` implements parse string tests for
  `TestAvoidGlobalsUse`.

Implementing a test is as simple as creating a test case that extends
`\tests\Psecio\Parse\ParseTest`. It must implement `parseSampleProvider()` and
`buildTest()`. The `buildTest()` method should return an instance of the unit
under test (e.g. `TestSessionRegenFalse`). Then `parseSampleProvider()` should
return a list of PHP code string (with initial `<?php` omitted) and result
pairs. Each PHP code string will be parsed, with the results evaluated against
the results of `buildTest()` via the `PhpParser\NodeTraverser`. If the results
match the result value, the test passes. Otherwise, it fails.

### CODE REVIEW

**Comment by redbeardcreator** [comment]
I played with trying to get things to work right with the autoloader but haven't come up with anything I like yet. I haven't given up yet, but will need to spend some more time with it. I had only intended to spend 15-20 minutes on it tonight but it's been nearly an hour :(

However, I *was* able to implement the assertion method. Well, three, actually. I turned the existing `evalTest()` method into `assertParseTestResult()` as a generic assertion method as well as the more specific `assertParseTestFalse()` and `assertParseTestTrue()`. Let me know what you think.

**Comment by hanneskod** [comment]
It looks good.  `parseSampleProvider` need not be abstract though, there could be an empty implementation, to support cases where only the assert methods are used.

And, oh, happy new year!

**Comment by redbeardcreator** [comment]
First, Happy New Year!

Second, I've attempted making `parseSampleProvider()` a concrete method that returns an empty array. When I do that, the error
```
No tests found in suite "Psecio\Parse\Tests\TestAvoidGlobalsUse_ParseTest::test_parseSample".
```
occurs (I used `TestAvoidGlobalsUse` as my guinea pig). It's marked as a warning, but PHPUnit considers it an error.

At this point I have a few options:

1. Leave `ParseTest` as is.
2. Refactor `ParseTest` into a base class with the assertions and a derived helper class that implements the easy-run `test_parseSample()` method and requires (via `abstract`) the `parseSampleProvider()` method.
3. Make the default `parseSampleProvider()` return `[ ['', true] ]`. That adds an extra, useless test if not overridden.
4. Convince PHPUnit the provider can be empty. But I haven't found a way to do that.

I'm leaning towards the second option right now. Any thoughts?

**Comment by redbeardcreator** [comment]
I was able to put all the `ParseTest` related tests and helpers into the `Psecio\Parse\Unittest` namespace. I think this works fairly cleanly.

Now the question becomes, should I start working on another PR to move all the unit tests into the `Unittest` namespace? I think this is a cleaner way to handle things (all tests and test-related classes are in a specified namespace). But I'm certainly open to suggestions.

**Comment by hanneskod** [comment]
There is also the 5th option of removing the dataProvider annotation and implement it on your own, iterating over the return of `parseSampleProvider` in `test_parseSample`.

Another issue completely: using a `PHPUnit_Framework_Constraint_IsEqual` seems to me to be bit overkill. As we are just comparing booleans a simple `assertSame` probably does the trick. And less important indeed: phpunit assertions usually take the expected value as the first argument, maybe switch the order of the arguments in `assertParseTestResult`.

I also think you could add some standard fail messages and refactor so that the scanning of the code snippets goes in a separate method. Maybe something like:

```php
<?php

namespace Psecio\Parse\Unittest;

use Psecio\Parse\Test;

abstract class ParseTest extends \PHPUnit_Framework_TestCase
{
    private $parser, $traverser, $visitor;

    abstract protected function buildTest();

    public function setUp()
    {
        $this->parser = new \PhpParser\Parser(new \PhpParser\Lexer\Emulative);
        $this->visitor = new ParseTestVisitor($this->buildTest());
        $this->traverser = new \PhpParser\NodeTraverser;
        $this->traverser->addVisitor($this->visitor);
    }

    protected function executeScan($code)
    {
        $this->visitor->result = true;
        $this->traverser->traverse(
            $this->parser->parse('<?php ' . $code)
        );
        return $this->visitor->result;
    }

    public function parseSampleProvider()
    {
        return [];
    }

    public function test_parseSample()
    {
        foreach ($this->parseSampleProvider() as $index => $args) {
            list($code, $result) = $args;
            $this->assertParseTest(
                $result,
                $code,
                "Failed asserting the result of sample #$index from " . get_class($this) . "::parseSampleProvider"
            );
        }
    }

    public function assertParseTest($expected, $code, $message = 'Failed asserting the result of a parser scan')
    {
        $this->assertSame($expected, $this->executeScan($code), $message);
    }

    public function assertParseTestFalse($code, $message = 'Failed asserting that the scanned code fails the test')
    {
        $this->assertParseTest(false, $code, $message);
    }

    public function assertParseTestTrue($code, $message = 'Failed asserting that the scanned code pass the test')
    {
        $this->assertParseTest(true, $code, $message);
    }
}
```

**Comment by hanneskod** [comment]
As for the namespace I personaly think that the extra `Unittest` namespace just makes the directory structure unnecessarily deep.

Also when using psr-0 then underscore represents a directory path. In psr-0 the class `TestSessionRegenFalse_ParseTest` should be in a file called `ParseTest.php` in the directory `TestSessionRegenFalse`. The testsuite works because phpunit does not use psr-0 when loading tests. But anyways...

**Comment by enygma** [comment]
Wow, this is awesome stuff....sorry I've been a bit behind in circling back around on this (holidays and all). Where does this currently stand @redbeardcreator? I see some suggestions from @hanneskod about things that could be updated but I don't want to merge unless you feel it's ready.

I appreciate all the work on this - this is excellent :)

**Comment by redbeardcreator** [comment]
@hanneskod On namespace, I kind of like putting the unit tests in a separate namespace. It keeps the tests from accidentally interfering with what's being tested. However, I can understand the depth issue. I don't have a problem with it personally, but I do understand. How does moving it higher up (say to `Psecio\Unittests`) or something like that sound?

I forgot about how PSR-0 works. I think I'll drop the underscore, but I might also move it to PSR-4. I think parse itself could be easily moved to PSR-4, as well, but I haven't checked to be sure. I'm relatively new to using namespaces, having spent a lot of time on legacy stuff. But I'm slowly migrating my primary legacy app to something more modern, so I'm trying to learn as much as I can.

My reason for using the `PHPUnit_Framework_Constraint_IsEqual` was so that I can implement the assertion as close to how PHPUnit does it as possible. It should also allow me to improve the messaging at a later date. I'd really like to include a bit from the parse tree on failures, as doing a `var_dump()` during test development has helped a lot in figuring out what I got wrong.

I'll have to look more into your more extensive change suggestion. I haven't had a chance to review it thoroughly yet. Maybe later tonight.

@enygma I'm fairly happy with the implementation as-is, but I definitely want to work on the namespace issue more.

I have several more unit tests written for other Tests, but they can definitely be pulled in at a later date. In implementing them I've found several issues that I've been working on, but they all need `ParseTest` before I can do a PR. And 

I'd say the general API of the `ParseTest ` is pretty stable at this point. There will be improvements to how things are processed, probably incorporating @hanneskod's suggestions, but I don't foresee anything that will break existing tests that rely on `ParseTest`, with the possible exception of a namespace change.

Finally, I have to merge in #25, as it may affect how the tests work.

So let me merge #25 and see where things stand. If I get feedback on the namespace change, I should have an update ready tonight. If not, I'll have the PR updated, but probably no namespace change. At that point, a merge is probably if you're ok with a possible future namespace change. I'll comment more when I get closer ;)

**Comment by redbeardcreator** [comment]
Ack...that broke things...badly.

Working on a new PR...this one isn't fixable without doing a force push.

**Comment by redbeardcreator** [comment]
Replaced with PR #26.

**Pull request closed without merging**
